### ISSUE TITLE
Feature Request: Show/Hide Faction to Players

### ISSUE THREAD

**Issue by GorgoPrimus** [mouse0270/kasper#10] opened 2023-06-21 01:59 UTC
It'd be really nice to be able to set up a full list of factions ahead of time in Kasper, and then hide all the ones the players haven't met yet until they do. This way all the faction stuff can be prepped ahead of time, instead of having to add them as you go (which necessitates a list elsewhere, which defeats part of the usefulness of this for me).

Thanks!

**Comment by mouse0270** [comment] 2023-06-21 02:37
This is a duplicate of issue #7 to keep my todo list simple, I am going to close this and reference issue #7

**Closed by mouse0270** 2023-06-21 02:37 UTC
