### ISSUE TITLE
Feature Request: Disable Mouse Wheel on Reputation Level Bars

### ISSUE THREAD

**Issue by GorgoPrimus** [mouse0270/kasper#11] opened 2023-06-21 02:07 UTC
Right now I want to use my mouse wheel to scroll down the list of factions, but I've found that if I do many of those factions have their reputations accidentally changed in the process because those bars are very sensitive to mouse wheel movement. Since for me the list of factions is bound to be somewhat long, whereas the range of affiliations isn't, I'd really appreciate if there was a setting or something to address this little issue.

**Comment by mouse0270** [comment] 2023-06-21 02:38
This is a duplicate of issue #6 to keep my todo list simple, I am going to close this and reference issue #6

**Closed by mouse0270** 2023-06-21 02:38 UTC
